service:
  name: screenshot-app
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  config: ${file(./config.json)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  bucket: ${self:custom.config.S3fileBucketName}
  accountsTable: ${self:custom.config.accountsTableName}
  imagesTable: ${self:custom.config.imagesTableName}
  collectionsTable: ${self:custom.config.collectionsTableName}
  sessionsTable: ${self:custom.config.sessionsTableName}
  customDomain: 
    domainName: ${self:custom.config.domain.name}
    basePath: ${self:custom.config.domain.basePath}
    stage: ${self:provider.stage}
    createRoute53Record: true
  serverless-offline:
    httpsProtocol: "../tls"
    httpPort: 3000

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.config.awsRegion}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: 
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.accountsTable}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.accountsTable}/index/*"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.imagesTable}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.imagesTable}/index/*"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.collectionsTable}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.collectionsTable}/index/*"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.sessionsTable}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.sessionsTable}/index/*"
        
    - Effect: "Allow"
      Action: 
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:DeleteObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  createAccount:
    handler: src/Lambdas/createAccount.handler
    events:
      - http:
          method: get
          path: createAccount
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  updateAccountInfo:
    handler: src/Lambdas/updateAccountInfo.handler
    events:
      - http:
          method: post
          path: updateAccountInfo
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true
      - http:
          path: updateAccountInfo
          method: options
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  logIn:
    handler: src/Lambdas/logIn.handler
    events:
      - http:
          method: post
          path: logIn
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  logOut:
    handler: src/Lambdas/logOut.handler
    events:
      - http:
          method: get
          path: logOut
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  verifySession:
    handler: src/Lambdas/verifySession.handler
    events:
      - http:
          method: get
          path: verifySession
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  getAccountInfo:
    handler: src/Lambdas/getAccountInfo.handler
    events:
      - http:
          method: get
          path: getAccountInfo
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  registerImage:
    handler: src/Lambdas/registerImage.handler
    events:
      - http:
          method: post
          path: registerImage
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  requestFileUpload:
    handler: src/Lambdas/requestFileUpload.handler
    events:
      - http:
          method: post
          path: requestFileUpload
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  uploadAvatar:
    handler: src/Lambdas/uploadAvatar.handler
    events:
      - http:
          method: post
          path: uploadAvatar
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  deleteFile:
    handler: src/Lambdas/deleteFile.handler
    events:
      - http:
          method: delete
          path: deleteFile
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  updateFileInfo:
    handler: src/Lambdas/updateFileInfo.handler
    events:
      - http:
          method: post
          path: updateFileInfo
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  searchForImage:
    handler: src/Lambdas/searchForImage.handler
    events:
      - http:
          method: get
          path: searchForImage
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  getImageFile:
    handler: src/Lambdas/getImageFile.handler
    events:
      - http:
          method: get
          path: image/{imageId}
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  getImage:
    handler: src/Lambdas/getImage.handler
    events:
      - http:
          method: get
          path: getImage
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  createCollection:
    handler: src/Lambdas/createCollection.handler
    events:
      - http:
          method: post
          path: createCollection
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  deleteCollection:
    handler: src/Lambdas/deleteCollection.handler
    events:
      - http:
          method: delete
          path: deleteCollection
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  getCollections:
    handler: src/Lambdas/getCollections.handler
    events:
      - http:
          method: get
          path: getCollections
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

  getImages:
    handler: src/Lambdas/getImages.handler
    events:
      - http:
          method: get
          path: getImages
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true
  updateCollectionInfo:
    handler: src/Lambdas/updateCollectionInfo.handler
    events:
      - http:
          method: post
          path: updateCollectionInfo
          cors:
            origin: '${self:custom.config.websiteUrl}'
            allowCredentials: true

resources:
  Resources:
    AccountsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.accountsTable}
        AttributeDefinitions:
          - AttributeName: hash
            AttributeType: S
        KeySchema:
          - AttributeName: hash
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    SessionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.sessionsTable}
        AttributeDefinitions:
          - AttributeName: sessionId
            AttributeType: S
        KeySchema:
          - AttributeName: sessionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CollectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.collectionsTable}
        AttributeDefinitions:
          - AttributeName: collectionId
            AttributeType: S
          - AttributeName: ownerHash
            AttributeType: S
        KeySchema:
          - AttributeName: collectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ownerHash-collectionId
            KeySchema:
            - AttributeName: ownerHash
              KeyType: HASH
            - AttributeName: collectionId
              KeyType: RANGE
            Projection: 
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    ImagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.imagesTable}
        AttributeDefinitions:
          - AttributeName: ownerHash
            AttributeType: S
          - AttributeName: collectionId
            AttributeType: S
          - AttributeName: imageId
            AttributeType: S
        KeySchema:
          - AttributeName: imageId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ownerHash-imageId
            KeySchema:
            - AttributeName: ownerHash
              KeyType: HASH
            - AttributeName: imageId
              KeyType: RANGE
            Projection: 
              ProjectionType: ALL
          - IndexName: collectionId-imageId
            KeySchema:
            - AttributeName: collectionId
              KeyType: HASH
            - AttributeName: imageId
              KeyType: RANGE
            Projection: 
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
